### PR TITLE
Fix Undefined Property Error in Google Map Component

### PR DESCRIPTION
**Pull request by alexcostaluiz**
Small fix for the Google map component.

### CODE REVIEW

**Comment by miahsanchez** [comment]
since you added keys to all the children could you add one to the info window?

**Comment by alexcostaluiz** [comment]
> since you added keys to all the children could you add one to the info window?
.
InfoWindow has no need for a key. They're only relevant for components in an array. If an array of components every changes (items removed, added, or index changes), keys let react know how to preserve state for the right components. Since InfoWindow is not part of an array of siblings it doesn't need a key.

**Comment by miahsanchez** [comment]
> > since you added keys to all the children could you add one to the info window?
> 
> InfoWindow has no need for a key. They're only relevant for components in an array. If an array of components every changes (items removed, added, or index changes), keys let react know how to preserve state for the right components. Since InfoWindow is not part of an array of siblings it doesn't need a key.

so then why does the you are here marker need one?

**Comment by alexcostaluiz** [comment]
> > > since you added keys to all the children could you add one to the info window?
> > 
> > 
> > InfoWindow has no need for a key. They're only relevant for components in an array. If an array of components every changes (items removed, added, or index changes), keys let react know how to preserve state for the right components. Since InfoWindow is not part of an array of siblings it doesn't need a key.
> 
> so then why does the you are here marker need one?

Ah yea I meant to mention, the Google Map uses keys of any marks during the whole distanceFromMouse thing so it seemed important that all markers have a key even though YouAreHere is not in an array.

**Pull request merged**
